### ISSUE TITLE
Question about ann_file from ${VEDADET_DIR}/configs/trainval/tinaface/tinaface.py for training or validation on WIDER FACE

### ISSUE THREAD

**Issue by swoook** [Media-Smart/vedadet#11]
Hi! First of all, thank you for your great work on single stage object detection!

I'm currently trying to reproduce detection results of **TinaFace** on **WIDER FACE val** written in the paper.

However, I have no idea about what file path I must write in [`ann_file`](https://github.com/swoook/vedadet/blob/3c1758c72262c32cb9c43aa133d1010828f8dc74/configs/trainval/tinaface/tinaface.py#L13) from *\${VEDADET_DIR}/configs/trainval/tinaface/tinaface.py* for WIDER FACE training or validation.

At fisrt, I suspected it should be *wider_face_train_bbx_gt.txt* or *wider_face_val_bbx_gt.txt* from [*wider_face_split.zip*](http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/support/bbx_annotation/wider_face_split.zip).

However, it seems [`fileio.list_from_file`](https://github.com/swoook/vedadet/blob/3c1758c72262c32cb9c43aa133d1010828f8dc74/vedadet/datasets/widerface.py#L32) from *\${VEDADET_DIR}/vedadet/datasets/widerface.py* doesn't return image ids appropriately.

According to the implementation of `fileio.list_from_file`, the appropriate file for `ann_file` seems to be a file containing only the image file name, such as *wider_face_test_filelist.txt* in from [*wider_face_split.zip*](http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/support/bbx_annotation/wider_face_split.zip).

Is it correct? Or am I missing something?

**Comment by hxcai** [comment]
@swoook please see [this](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface) for data preparing.

**Comment by swoook** [comment]
Thank you for your response :) 

However, I already followed the instructions from [Data](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface#data) section.

```
.
├── 0_Parade_marchingband_1_1004.xml
├── 0_Parade_marchingband_1_1045.xml
├── 0_Parade_marchingband_1_104.xml
├── 0_Parade_marchingband_1_139.xml
├── 0_Parade_marchingband_1_147.xml
├── 0_Parade_marchingband_1_149.xml
├── 0_Parade_marchingband_1_156.xml
├── 0_Parade_marchingband_1_172.xml
├── 0_Parade_marchingband_1_188.xml
...
```

**My question is: What is the appropriate file for `ann_file` from [*configs/trainval/tinaface/tinaface.py*](https://github.com/Media-Smart/vedadet/blob/main/configs/trainval/tinaface/tinaface.py#L37) for WIDER FACE validation?**

```
        ann_file=data_root + 'WIDER_val/val.txt',
```

Maybe it would be better to explain my issue step by step.

[**Evaluation**](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface#evaluation) section doesn't provide any information about config.

> ## Evaluation
>
> a. Back to `${vedadet_root}`
>
> b. Run following instruction
>
> ```shell
> python config/trainval/tinaface/test_widerface.py configs/trainval/tinaface/tinaface.py weight_path
> ```
>
> widerface txt file will be generated at `${vedadet_root}/eval_dirs/tmp/tinaface/`, and then download the [eval_tool](http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/support/eval_script/eval_tools.zip) to evaluate the WIDERFACE performance.

But [**Training**](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface#train) and [**Infer**](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface#infer) sections suggest to follow the official instructions on [vedadet](https://github.com/Media-Smart/vedadet#train) for training and inference, respectively.

> ## Train
>
> a. Follow the official instructions on [vedadet](https://github.com/Media-Smart/vedadet) 

And [vedadet](https://github.com/Media-Smart/vedadet#train) provides [*configs/trainval/retinanet/retinanet.py*](https://github.com/Media-Smart/vedadet/blob/main/configs/trainval/retinanet/retinanet.py) as an example for config.

> ## Train
>
> a. Config
>
> Modify some configuration accordingly in the config file like `configs/trainval/retinanet.py`

 In [*configs/trainval/retinanet/retinanet.py*](https://github.com/Media-Smart/vedadet/blob/main/configs/trainval/retinanet/retinanet.py), `ann_file` is *instances_train2017.json* by default.

```
        ann_file=data_root + 'annotations/instances_train2017.json',
```

 In [*configs/trainval/tinaface/tinaface.py*](https://github.com/Media-Smart/vedadet/blob/main/configs/trainval/tinaface/tinaface.py#L37), `ann_file` is *val.txt* by default.

```
        ann_file=data_root + 'WIDER_val/val.txt',
```

However, *val.txt* isn't provided by [WIDER FACE](http://shuoyang1213.me/WIDERFACE/) or [akofman/wider-face-pascal-voc-annotations](https://github.com/akofman/wider-face-pascal-voc-annotations).

And as I mentioned before, `wider_face_val_bbx_gt.txt` seems to be not appropriate for `ann_file`.

![debug-img-ids](https://user-images.githubusercontent.com/43327019/100874744-5fd84c80-34e8-11eb-9eb2-da7c1cfc9645.png)

I think I should create *val.txt* which contains only the image file name, such as *wider_face_test_filelist.txt* from [wider_face_split.zip](http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/support/bbx_annotation/wider_face_split.zip) myself. Is it correct?

**Comment by mike112223** [comment]
@swoook  we update the details for data preparation, please check README in [this](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface).

**Comment by swoook** [comment]
Thanks a lot! 😄
