### ISSUE TITLE
Pretrained

### ISSUE THREAD

**Issue by CengizhanYurdakul** [Media-Smart/vedadet#14]
I could not find the pretrained model. Where can I download it?

**Comment by hxcai** [comment]
@CengizhanYurdakul Hi, which pretrained model do u want?

**Comment by hxcai** [comment]
@CengizhanYurdakul You can download models from [mmdetection](https://github.com/open-mmlab/mmdetection) and you need to extract weights to save a new file like following
```shell
model = torch.load(mmdetection_model_file)
weights = model['state_dict']
torch.save(weights, vedadet_weight_file)
```

**Comment by CengizhanYurdakul** [comment]
> @CengizhanYurdakul Hi, which pretrained model do u want?

I found this repo from PaperswithCode. I am looking for state of the art face detection model.

**Comment by hxcai** [comment]
@CengizhanYurdakul Please see [this](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface) for details.

**Comment by abhisheksrinivasan2811** [comment]
Can you point the tinaface pretrained model?
