### ISSUE TITLE
how to inference on webcam or video?

### ISSUE THREAD

**Issue by hyperf0cus** [Media-Smart/vedadet#15]
In infer.py you did it by data_pipeline. How to handle it when source is Webcam or Video frames?

**Comment by hxcai** [comment]
@hyperf0cus You can remove the transform LoadImageFromFile, and construct a same dict after reading image.

**Comment by hyperf0cus** [comment]
> @hyperf0cus You can remove the transform LoadImageFromFile, and construct a same dict after reading image.

Thank you!

**Comment by gd1925** [comment]
Hi, 
I am trying to run the code for a mp4 video, but I cant seem to understand what you mean by "construct a same dict after reading image". Could you please help? Thank you very much.

**Comment by lixinru77** [comment]
do you solve this problem?
please help me to come true.thank you
