### ISSUE TITLE
Run from a pretrained model.

### ISSUE THREAD

**Issue by abhisheksrinivasan2811** [Media-Smart/vedadet#16]
Hey I'm getting this error when I try to run the tinaface.py file with the pretrained model.Can you help me out?

Traceback (most recent call last):
  File "tools/infer.py", line 93, in <module>
    main()
  File "tools/infer.py", line 75, in main
    engine, data_pipeline, device = prepare(cfg)
  File "tools/infer.py", line 31, in prepare
    load_weights(engine.model, cfg.weights.filepath)
  File "/content/vedadet/configs/vedadet/vedacore/misc/checkpoint.py", line 238, in load_weights
    state_dict = _load_checkpoint(filepath, map_location)
  File "/content/vedadet/configs/vedadet/vedacore/misc/checkpoint.py", line 135, in _load_checkpoint
    raise IOError(f'{filepath} is not a file')
OSError: your/weight/file/path is not a file

**Comment by hxcai** [comment]
@abhisheksrinivasan2811 Please modify the weights in config file

**Comment by abhisheksrinivasan2811** [comment]
I uploaded the pretrained model given in the gDrive.

**Comment by hxcai** [comment]
@abhisheksrinivasan2811 Sorry, I don't understand what you mean uploading the pretrained model?

**Comment by abhisheksrinivasan2811** [comment]
I meant.After modifying the config file.I'm getting this error.

**Comment by hxcai** [comment]
@abhisheksrinivasan2811 How do you run the inference?

**Comment by abhisheksrinivasan2811** [comment]
CUDA_VISIBLE_DEVICES="0" python tools/infer.py configs/infer/retinanet/retinanet.py image_path.Replacing Tinanet.py  here and the model path.

**Comment by hxcai** [comment]
@abhisheksrinivasan2811 Where you put the pretrained model file?
