### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by StetchPlane** [Media-Smart/vedadet#27]
When the training is interrupted at epoch70, the effect will drop sharply whether the training is continued at epoch70 or epoch60.

epoch 60:
![60](https://user-images.githubusercontent.com/46260162/103255591-ce63d980-49c4-11eb-973c-abc1a585c550.png)
training from epoch70, the result of epoch 90:
![70-90](https://user-images.githubusercontent.com/46260162/103255728-6497ff80-49c5-11eb-98ac-277c4b0625a7.png)
training from epoch60, the result of epoch 90:
![90](https://user-images.githubusercontent.com/46260162/103255641-0408c280-49c5-11eb-81fc-e12affb4b3ad.png)

May I ask what causes this?

**Comment by hxcai** [comment]
@StetchPlane Do you reload model weight, optimizer and meta data?

**Comment by StetchPlane** [comment]
Yes, I loaded them all

**Comment by mike112223** [comment]
Hi @StetchPlane,
Can you provide the training logs and config files?

**Comment by StetchPlane** [comment]
I seem to know the reason. I didn't delete "prefix = backbone" when loading weights. Thank you for your reply.
