### ISSUE TITLE
How about TinaFace performance?

### ISSUE THREAD

**Issue by mstaryi** [Media-Smart/vedadet#3]
How about TinaFace performance?

**Comment by hxcai** [comment]
@mstaryi Hi, please see [this](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface) for detail

**Comment by mstaryi** [comment]
@hxcai Oh, I mean how many milliseconds it takes for a picture to get the det result

**Comment by hxcai** [comment]
@mstaryi It takes about 500ms with the default configuration and Nvidia 1080Ti GPU. For application, u may set higher score_thr, smaller image input size, using TensorRT and etc..
