### ISSUE TITLE
您好，我自己想训练自己的数据集，但是一直加载有问题，请问一下我不想加载使用resnet50的预训练模型，我该更改什么地方呢，谢谢您

### ISSUE THREAD

**Issue by juliusyang97** [Media-Smart/vedadet#35]

**Comment by juliusyang97** [comment]
我像只加载resnet50网络结构，你加载官方的预训练模型，这种方法可行吗；
我查了pytorch加载预训练模型的方法，但是我没有在本项目中找到如何更改

**Comment by mike112223** [comment]
If you do not want to use pretrained model, you can simply delete the "weights" in config.
