### ISSUE TITLE
tinaface_r50_fpn_widerface.pth mAP仅0.628

### ISSUE THREAD

**Issue by dan520520520** [Media-Smart/vedadet#36]
tinaface_r50_fpn_widerface.pth测试，按照Issues #25的过程做了一遍，还是下面的结果，做了filter_widerface_val.py以后感觉xml没什么变化?
+-------+-------+---------+--------+-------+
| class | gts | dets | recall | ap |
+-------+-------+---------+--------+-------+
| face | 31957 | 8420592 | 0.837 | 0.628 |
+-------+-------+---------+--------+-------+
| mAP | | | | 0.628 |
+-------+-------+---------+--------+-------+

**Comment by mike112223** [comment]
Please follow the newest official instructions ([this](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface)) to do the testing. If you still get wrong results, please provide the complete testing log.

**Comment by dan520520520** [comment]
![Uploading 图片.png…]()

**Comment by dan520520520** [comment]
@mike112223 filter_widerface_val.py时会遇到中断，把assert np.sum(bbox == gt_box) == 4注释掉了，有影响吗？

**Comment by mike112223** [comment]
Have you solved the problem? I followed the instructions again, and i did not stuck at running filter_widerface_val.py.

**Comment by dan520520520** [comment]
> 
> 
> Have you solved the problem? I followed the instructions again, and i did not stuck at running filter_widerface_val.py.
解决了，dict(typename='Resize', keep_ratio=True)，我之前keep_ratio=False关掉了，打开就可以了。我是按照步骤做，达到了0.923.

**Comment by dan520520520** [comment]
不运行filter_widerface_val.py，可以达到0.923吗？

**Comment by mike112223** [comment]
Check #24. If you skip this step, some extremely hard faces will be token into account in evaluation, which will definitely make the score low.

**Comment by twmht** [comment]
@mike112223 

is filtering bounding box necessary?

I did not see the same thing in retinaface (https://github.com/biubug6/Pytorch_Retinaface/blob/master/test_widerface.py)

**Comment by mileistone** [comment]
> @mike112223
> 
> is filtering bounding box necessary?
> 
> I did not see the same thing in retinaface (https://github.com/biubug6/Pytorch_Retinaface/blob/master/test_widerface.py)

It's necessary.

**Comment by twmht** [comment]
@mileistone 

can you provide the reference?

**Comment by mileistone** [comment]
It's a postprocessing method proposed by us, there is no reference.

**Comment by twmht** [comment]
@mileistone 

I change the backbone to mobilnet0.25 in order to reproduce a better result than https://github.com/biubug6/Pytorch_Retinaface.

However, the result is inferior, for example, the easy set is  84.8 vs 88.67. they use ohem which is inferior than focal loss in theory. Do you have any idea？
