### ISSUE TITLE
About img_norm_cfg in tinaface.py

### ISSUE THREAD

**Issue by WolffyChen** [Media-Smart/vedadet#37]
Thanks for this great work. Tinaface use resnet50 as backbone and download pretrained model from pytorch official website. The official pytorch resnet50 use norm std as [58.395, 57.12, 57.375], whereas the std of img_norm_cfg in tinaface.py is [1, 1, 1]. Is there something I understand wrong?

**Comment by mike112223** [comment]
In order to better demonstrate the efficiency of our method, we keep the data part same as Retinaface where the std of img_norm_cfg is [1, 1, 1]. And DSFD also uses [1, 1, 1]. Actually, we did not dig into this point.

**Comment by WolffyChen** [comment]
Thank you for your reply. It may be that the std has little effect on pretrained model initialization. And I will try to change the std to [58.395, 57.12, 57.375] to test the performance.

**Comment by mike112223** [comment]
If you do not train with [58.395, 57.12, 57.375] and directly use this configuration to test, the performance will definitely degrade.

**Comment by WolffyChen** [comment]
Yeah, I mean I will train with [58.395, 57.12, 57.375] first and then test it.
