### ISSUE TITLE
Training tinaface on mmdetection 

### ISSUE THREAD

**Issue by yossibiton** [Media-Smart/vedadet#40]
I'm trying to train a compatible model to tinaface on mmdetection repo.
The only difference is that I don't use the IOU-aware head, but normal RetinaHead.

On the first batches, I can see that on mmdetection the bbox loss is twice higher than vedadet. Maybe you can explain that?
Do you use different weights initialization than mmdetection?
I was really surprised by that because I see your code is based on mmdetection (it actually a fork, although you didn't use github fork)

**Comment by mileistone** [comment]
you'd better use vedadet.

**Comment by yossibiton** [comment]
Why should I prefer it ?
It looks like you copied the code from mmdetection, and implemented the
IoUAware head.
Can you explain why didn't you use git fork ?

**Comment by mileistone** [comment]
We re-design MMDetection based on our taste and needs, it's not the same as MMDetection, you may spend some time to compare vedadet and MMDetection if you have interest. If you like MMDetection, you can also use MMDetection, it's OK.
