### ISSUE TITLE
Can not find the file  val.xml

### ISSUE THREAD

**Issue by Watebear** [Media-Smart/vedadet#46]
Thank you for sharing the codes!
I tried to run your code but meet an error:

FileNotFoundError: [Errno 2] No such file or directory: '/home/dddzz/worksapce/Datasets/WIDERFace/WIDER_val/Annotations/val.xml'

How can I get the file, val.xml ?

**Comment by hxcai** [comment]
@Watebear Please following this [link](https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface) to prepare data.
