### ISSUE TITLE
is there a way to tackle more than one image ?

### ISSUE THREAD

**Issue by fitoule** [Media-Smart/vedadet#48]
Hi is there a way to tackle more than one image ?
i set the path as an image directory, it tackles only one and says that others are error ?

command line 
CUDA_VISIBLE_DEVICES="0" python tools/infer.py configs/infer/tinaface/tinaface.py /mnt/disk6T0/test/img/*

output
infer.py: error: unrecognized arguments: /mnt/disk6T0/test/img/2.jpeg

**Comment by hxcai** [comment]
@fitoule The infer code is an example to process single image, you can modify this code to handle more than one image.
