### ISSUE TITLE
Maybe a bug in assembler/trainval.py

### ISSUE THREAD

**Issue by felixfuu** [Media-Smart/vedadet#63]
The models in train/val engine are different, and it's maybe a bug in the validation phase. 

https://github.com/Media-Smart/vedadet/blob/main/vedadet/assembler/trainval.py#L27
https://github.com/Media-Smart/vedadet/blob/main/vedadet/assembler/trainval.py#L51
@mileistone

**Comment by mileistone** [comment]
We notice it and solved this problem by singleton_arg in https://github.com/Media-Smart/vedadet/blob/aaf3b3bc3c7944aba1cc28138165d403023a9152/vedadet/models/builder.py#L44
