### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by wangwangteam** [Media-Smart/vedadet#9]
(veda) root@linkdata-X299-WU8:/media/linkdata/zs/vedadet# bash tools/dist_trainval.sh configs/trainval/retinanet/retinanet.py 0
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
2020-12-02 11:57:16,139 - vedadet - INFO - Loading weights from /media/linkdata/zs/vedadet/premodel/resnet50-19c8e357.pth
2020-12-02 11:57:16,316 - vedadet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: backbone.fc.weight, backbone.fc.bias

missing keys in source state_dict: neck.lateral_convs.0.conv.weight, neck.lateral_convs.0.conv.bias, neck.lateral_convs.1.conv.weight, neck.lateral_convs.1.conv.bias, neck.lateral_convs.2.conv.weight, neck.lateral_convs.2.conv.bias, neck.fpn_convs.0.conv.weight, neck.fpn_convs.0.conv.bias, neck.fpn_convs.1.conv.weight, neck.fpn_convs.1.conv.bias, neck.fpn_convs.2.conv.weight, neck.fpn_convs.2.conv.bias, neck.fpn_convs.3.conv.weight, neck.fpn_convs.3.conv.bias, neck.fpn_convs.4.conv.weight, neck.fpn_convs.4.conv.bias, bbox_head.cls_convs.0.conv.weight, bbox_head.cls_convs.0.conv.bias, bbox_head.cls_convs.1.conv.weight, bbox_head.cls_convs.1.conv.bias, bbox_head.cls_convs.2.conv.weight, bbox_head.cls_convs.2.conv.bias, bbox_head.cls_convs.3.conv.weight, bbox_head.cls_convs.3.conv.bias, bbox_head.reg_convs.0.conv.weight, bbox_head.reg_convs.0.conv.bias, bbox_head.reg_convs.1.conv.weight, bbox_head.reg_convs.1.conv.bias, bbox_head.reg_convs.2.conv.weight, bbox_head.reg_convs.2.conv.bias, bbox_head.reg_convs.3.conv.weight, bbox_head.reg_convs.3.conv.bias, bbox_head.retina_cls.weight, bbox_head.retina_cls.bias, bbox_head.retina_reg.weight, bbox_head.retina_reg.bias

2020-12-02 11:57:16,473 - vedadet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: backbone.fc.weight, backbone.fc.bias

missing keys in source state_dict: neck.lateral_convs.0.conv.weight, neck.lateral_convs.0.conv.bias, neck.lateral_convs.1.conv.weight, neck.lateral_convs.1.conv.bias, neck.lateral_convs.2.conv.weight, neck.lateral_convs.2.conv.bias, neck.fpn_convs.0.conv.weight, neck.fpn_convs.0.conv.bias, neck.fpn_convs.1.conv.weight, neck.fpn_convs.1.conv.bias, neck.fpn_convs.2.conv.weight, neck.fpn_convs.2.conv.bias, neck.fpn_convs.3.conv.weight, neck.fpn_convs.3.conv.bias, neck.fpn_convs.4.conv.weight, neck.fpn_convs.4.conv.bias, bbox_head.cls_convs.0.conv.weight, bbox_head.cls_convs.0.conv.bias, bbox_head.cls_convs.1.conv.weight, bbox_head.cls_convs.1.conv.bias, bbox_head.cls_convs.2.conv.weight, bbox_head.cls_convs.2.conv.bias, bbox_head.cls_convs.3.conv.weight, bbox_head.cls_convs.3.conv.bias, bbox_head.reg_convs.0.conv.weight, bbox_head.reg_convs.0.conv.bias, bbox_head.reg_convs.1.conv.weight, bbox_head.reg_convs.1.conv.bias, bbox_head.reg_convs.2.conv.weight, bbox_head.reg_convs.2.conv.bias, bbox_head.reg_convs.3.conv.weight, bbox_head.reg_convs.3.conv.bias, bbox_head.retina_cls.weight, bbox_head.retina_cls.bias, bbox_head.retina_reg.weight, bbox_head.retina_reg.bias

**Comment by hxcai** [comment]
@wangwangteam I think this is not an error but a warning

**Comment by wangwangteam** [comment]
When I had this problem, he didn't go on

**Comment by hxcai** [comment]
@wangwangteam It seems working well, you could wait for a while.

**Comment by juliusyang97** [comment]
我等了一下午，他也没有进行下去，一直在这卡在这 和这个问题一模一样  #21
