### ISSUE TITLE
ONNX Export

### ISSUE THREAD

**Issue by kanybekasanbekov** [Media-Smart/vedadet#95]
I have been struggling to install vedadet on my local computer. I have encountered errors after the command `pip install -v -e .`, the error was about the CUDA. I spent an enormous amount of time trying to fix it, still didn't succeed. However, I was able to install, run and export to ONNX on Colab. Here is my simple code that I want to share with others:
https://gist.github.com/kanybekasanbekov/9b5c9293e26905255b29c421e881e129

I hope it will be useful to someone.

**Comment by TranThanh96** [comment]
@kanybekasanbekov I still can not build on colab, could you upload and share your onnx file ? many thanks

**Comment by kanybekasanbekov** [comment]
Hi, I've uploaded the ONNX file [here](https://drive.google.com/file/d/1KGTru2-EeEbXORHtprUeC-57eDAXldTb/view?usp=sharing)

**Comment by TranThanh96** [comment]
hi, thank you @kanybekasanbekov . Can you share me your detect face code with that model onnx.
